s = set()
n = input("enter number1  :")
s.add(int(n))
n = input("enter number2  :")
s.add(int(n))
n = input("enter number3  :")
s.add(int(n))
n = input("enter number4  :")
s.add(int(n))
n = input("enter number5  :")
s.add(int(n))
n = input("enter number6  :")
s.add(int(n))
n = input("enter number7  :")
s.add(int(n))
n = input("enter number8  :")
s.add(int(n))
n = input("enter number9  :")
s.add(int(n))
print(s)